//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class Home : Neo.ApplicationFramework.Controls.Controls.Form, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage {
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_aInput;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_bInput;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_aLabel;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_bLabel;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_TriggerWalker;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Title;
        
        private Neo.ApplicationFramework.Controls.Controls.TextBox m_Render;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_UpdateGrid;
        
        private bool m_Initialized_Home;
        
        public Home() {
            this.InitializeComponent();
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter aInput {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_aInput);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter bInput {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_bInput);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter aLabel {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_aLabel);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter bLabel {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_bLabel);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter TriggerWalker {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_TriggerWalker);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Title {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Title);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextBoxCFAdapter Render {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextBoxCFAdapter>(this.m_Render);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter UpdateGrid {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_UpdateGrid);
            }
        }
        
        private void InitializeComponent() {
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            this.m_aInput = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_bInput = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_aLabel = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_bLabel = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Line = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_TriggerWalker = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Title = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Render = new Neo.ApplicationFramework.Controls.Controls.TextBox();
            this.m_UpdateGrid = new Neo.ApplicationFramework.Controls.Controls.Button();
            ((System.ComponentModel.ISupportInitialize)(this.m_aInput)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_bInput)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_aLabel)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_bLabel)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_TriggerWalker)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Title)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Render)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_UpdateGrid)).BeginInit();
            this.SuspendLayout();
            // 
            // Home
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.SingleBorder;
            this.ControlBox = false;
            // 
            // m_aInput
            // 
            this.m_aInput.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_aInput.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_aInput.BlinkDynamicsValue = false;
            this.m_aInput.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_aInput.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_aInput.DelayMouseInputPeriod = 0;
            this.m_aInput.EnabledDynamicsValue = true;
            this.m_aInput.FontSizePixels = 20;
            this.m_aInput.Height = 70;
            this.m_aInput.Left = 71;
            this.m_aInput.Name = "m_aInput";
            this.m_aInput.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_aInput.ScreenOwnerName = "Home";
            this.m_aInput.Top = 88;
            this.m_aInput.VisibleDynamicsValue = true;
            this.m_aInput.Width = 190;
            // 
            // m_bInput
            // 
            this.m_bInput.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_bInput.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_bInput.BlinkDynamicsValue = false;
            this.m_bInput.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_bInput.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_bInput.DelayMouseInputPeriod = 0;
            this.m_bInput.EnabledDynamicsValue = true;
            this.m_bInput.FontSizePixels = 20;
            this.m_bInput.Height = 70;
            this.m_bInput.Left = 71;
            this.m_bInput.Name = "m_bInput";
            this.m_bInput.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_bInput.ScreenOwnerName = "Home";
            this.m_bInput.Top = 171;
            this.m_bInput.VisibleDynamicsValue = true;
            this.m_bInput.Width = 190;
            // 
            // m_aLabel
            // 
            this.m_aLabel.BlinkDynamicsValue = false;
            this.m_aLabel.DelayMouseInputPeriod = 0;
            this.m_aLabel.EnabledDynamicsValue = true;
            this.m_aLabel.FontSizePixels = 20;
            this.m_aLabel.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_aLabel.Height = 21;
            this.m_aLabel.Left = 23;
            this.m_aLabel.Name = "m_aLabel";
            this.m_aLabel.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 0D, 5D, 1D);
            this.m_aLabel.ScreenOwnerName = "Home";
            this.m_aLabel.Top = 108;
            this.m_aLabel.VisibleDynamicsValue = true;
            this.m_aLabel.Width = 12;
            // 
            // m_bLabel
            // 
            this.m_bLabel.BlinkDynamicsValue = false;
            this.m_bLabel.DelayMouseInputPeriod = 0;
            this.m_bLabel.EnabledDynamicsValue = true;
            this.m_bLabel.FontSizePixels = 20;
            this.m_bLabel.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_bLabel.Height = 21;
            this.m_bLabel.Left = 23;
            this.m_bLabel.Name = "m_bLabel";
            this.m_bLabel.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 0D, 5D, 1D);
            this.m_bLabel.ScreenOwnerName = "Home";
            this.m_bLabel.Top = 191;
            this.m_bLabel.VisibleDynamicsValue = true;
            this.m_bLabel.Width = 12;
            // 
            // m_Line
            // 
            this.m_Line.BlinkDynamicsValue = false;
            this.m_Line.DelayMouseInputPeriod = 0;
            this.m_Line.EnabledDynamicsValue = true;
            this.m_Line.Fill = null;
            this.m_Line.Name = "m_Line";
            this.m_Line.ScreenOwnerName = "Home";
            this.m_Line.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line.VisibleDynamicsValue = true;
            this.m_Line.X1 = 285;
            this.m_Line.X2 = 285;
            this.m_Line.Y1 = -2;
            this.m_Line.Y2 = 478;
            // 
            // m_TriggerWalker
            // 
            this.m_TriggerWalker.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_TriggerWalker.BlinkDynamicsValue = false;
            this.m_TriggerWalker.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_TriggerWalker.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_TriggerWalker.DelayMouseInputPeriod = 0;
            this.m_TriggerWalker.EnabledDynamicsValue = true;
            this.m_TriggerWalker.FontSizePixels = 15;
            this.m_TriggerWalker.ForceTransparency = true;
            this.m_TriggerWalker.Height = 81;
            this.m_TriggerWalker.IndicatorMargin = null;
            this.m_TriggerWalker.Left = 23;
            this.m_TriggerWalker.Name = "m_TriggerWalker";
            this.m_TriggerWalker.RequiresTransparency = true;
            this.m_TriggerWalker.ScreenOwnerName = "Home";
            this.m_TriggerWalker.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_TriggerWalker.TextHeight = 18;
            this.m_TriggerWalker.TextValue = 0D;
            this.m_TriggerWalker.TextWidth = 228;
            this.m_TriggerWalker.Top = 382;
            this.m_TriggerWalker.Value = 0D;
            this.m_TriggerWalker.VisibleDynamicsValue = true;
            this.m_TriggerWalker.VisualPropertiesHashCode = -1135629592;
            this.m_TriggerWalker.Width = 238;
            // 
            // m_Title
            // 
            this.m_Title.BlinkDynamicsValue = false;
            this.m_Title.DelayMouseInputPeriod = 0;
            this.m_Title.EnabledDynamicsValue = true;
            this.m_Title.FontSizePixels = 36;
            this.m_Title.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Title.Height = 21;
            this.m_Title.Left = 29;
            this.m_Title.Name = "m_Title";
            this.m_Title.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(9D, 0D, 9D, 1D);
            this.m_Title.ScreenOwnerName = "Home";
            this.m_Title.Top = 11;
            this.m_Title.VisibleDynamicsValue = true;
            this.m_Title.Width = 71;
            // 
            // m_Render
            // 
            this.m_Render.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Render.BlinkDynamicsValue = false;
            this.m_Render.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(143)))), ((int)(((byte)(164)))), ((int)(((byte)(190))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Render.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Render.DelayMouseInputPeriod = 0;
            this.m_Render.EnabledDynamicsValue = true;
            this.m_Render.FontSizePixels = 10;
            this.m_Render.Height = 450;
            this.m_Render.Left = 307;
            this.m_Render.MultiLine = true;
            this.m_Render.Name = "m_Render";
            this.m_Render.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF();
            this.m_Render.ReadOnly = true;
            this.m_Render.ScreenOwnerName = "Home";
            this.m_Render.Top = 13;
            this.m_Render.VisibleDynamicsValue = true;
            this.m_Render.Width = 476;
            // 
            // m_UpdateGrid
            // 
            this.m_UpdateGrid.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_UpdateGrid.BlinkDynamicsValue = false;
            this.m_UpdateGrid.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_UpdateGrid.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_UpdateGrid.DelayMouseInputPeriod = 0;
            this.m_UpdateGrid.EnabledDynamicsValue = true;
            this.m_UpdateGrid.FontSizePixels = 15;
            this.m_UpdateGrid.ForceTransparency = true;
            this.m_UpdateGrid.Height = 81;
            this.m_UpdateGrid.IndicatorMargin = null;
            this.m_UpdateGrid.Left = 23;
            this.m_UpdateGrid.Name = "m_UpdateGrid";
            this.m_UpdateGrid.RequiresTransparency = true;
            this.m_UpdateGrid.ScreenOwnerName = "Home";
            this.m_UpdateGrid.SymbolIntervalMapper = symbolintervalmapper2;
            this.m_UpdateGrid.TextHeight = 18;
            this.m_UpdateGrid.TextValue = 0D;
            this.m_UpdateGrid.TextWidth = 228;
            this.m_UpdateGrid.Top = 289;
            this.m_UpdateGrid.Value = 0D;
            this.m_UpdateGrid.VisibleDynamicsValue = true;
            this.m_UpdateGrid.VisualPropertiesHashCode = -1135629592;
            this.m_UpdateGrid.Width = 238;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(800, 480);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "Home";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_Home = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_Home) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_aInput);
            this.DrawingPrimitives.Add(this.m_bInput);
            this.DrawingPrimitives.Add(this.m_aLabel);
            this.DrawingPrimitives.Add(this.m_bLabel);
            this.DrawingPrimitives.Add(this.m_Line);
            this.DrawingPrimitives.Add(this.m_TriggerWalker);
            this.DrawingPrimitives.Add(this.m_Title);
            this.DrawingPrimitives.Add(this.m_Render);
            this.DrawingPrimitives.Add(this.m_UpdateGrid);
            ((System.ComponentModel.ISupportInitialize)(this.m_aInput)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_bInput)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_aLabel)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_bLabel)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_TriggerWalker)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Title)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Render)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_UpdateGrid)).EndInit();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Home));
            this.m_aLabel.Text = resources.GetText("Home.aLabel.Text", "a");
            this.m_bLabel.Text = resources.GetText("Home.bLabel.Text", "b");
            this.m_TriggerWalker.Text = resources.GetText("Home.TriggerWalker.Text", "Start");
            this.m_Title.Text = resources.GetText("Home.Title.Text", "Border Patrol");
            this.m_UpdateGrid.Text = resources.GetText("Home.UpdateGrid.Text", "Update Grid");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage() {
            this.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_Home) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding1 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.aValue"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_aInput.DataBindings.Add(dynamicBinding1);
            this.m_DynamicBindings.Add(dynamicBinding1);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding2 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.bValue"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_bInput.DataBindings.Add(dynamicBinding2);
            this.m_DynamicBindings.Add(dynamicBinding2);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding3 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Text", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.BorderRender"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.RawConverterCF.Default);
            this.m_Render.DataBindings.Add(dynamicBinding3);
            this.m_DynamicBindings.Add(dynamicBinding3);
        }
    }
}
